spring.application.name=productmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

